# Generated by Django 4.1.5 on 2023-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='about_banner',
        ),
        migrations.RemoveField(
            model_name='person',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile_pic_alt',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
