# Generated by Django 4.1.5 on 2023-01-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_person_about_banner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Me_shorts',
            new_name='Achievements',
        ),
    ]
