# Generated by Django 4.1.5 on 2023-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_person_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
