# Generated by Django 4.1.5 on 2023-01-20 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_person_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('preview_pic', models.ImageField(blank=True, default='project_images/default.jpg', upload_to='project_images')),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('preview_text', models.CharField(blank=True, max_length=50, null=True)),
                ('preview_link', models.CharField(blank=True, max_length=200, null=True)),
                ('source_code_text', models.CharField(blank=True, max_length=50, null=True)),
                ('source_code_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='google_map_embed_src',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.CreateModel(
            name='Project_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('img', 'Image'), ('yt_link', 'YouTube Video'), ('vid', 'Uploaded Video')], default='img', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('youtube_embed_link', models.CharField(blank=True, max_length=600, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'avi', 'flv'])])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_category'),
        ),
        migrations.AddField(
            model_name='project',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
    ]
