# Generated by Django 4.1.5 on 2023-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
