# Generated by Django 4.1.5 on 2023-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_education_title_alter_experience_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
