# Generated by Django 4.1.5 on 2023-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_education_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_slide',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
    ]
