# Generated by Django 4.1.5 on 2023-01-20 19:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_project_slide_video_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField()),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('content', ckeditor.fields.RichTextField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
