# Generated by Django 4.1.5 on 2023-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
