# Generated by Django 4.1.5 on 2023-01-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_social_media_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
